---
name: Documentation Issue
about: Report an issue with the documentation
title: '[DOCS] '
labels: documentation
assignees: ''
---

**Documentation page**
Please provide a link to the documentation page or specify which part of the docs this relates to:
- URL: 
- Section: 

**Issue description**
A clear and concise description of what is wrong or missing in the documentation.

**Type of issue** (check all that apply)
- [ ] Typo or grammatical error
- [ ] Incorrect information
- [ ] Missing information
- [ ] Unclear explanation
- [ ] Missing example
- [ ] Broken link
- [ ] Other

**Suggested improvement**
If you have a suggestion for how to fix or improve the documentation, please describe it here.

**Additional context**
Add any other context about the documentation issue here.
