---
name: Feature Request
about: Suggest an idea or enhancement for PINNx
title: '[FEATURE] '
labels: enhancement
assignees: ''
---

**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

**Use case**
Describe the use case for this feature. How would it benefit PINNx users?

**Example usage**
If applicable, provide a code example of how you envision this feature being used:

```python
import pinnx
# Example code showing the proposed feature
```

**Additional context**
Add any other context, screenshots, or references about the feature request here.

**Would you be willing to contribute this feature?**
- [ ] Yes, I can submit a PR
- [ ] I need help implementing this
- [ ] I'm just suggesting the idea
